"""Init schema

Revision ID: 2e07f6b55afd
Revises: 
Create Date: 2025-07-24 12:24:45.639418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2e07f6b55afd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("client_secret", sa.String(), nullable=True),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.Column("webhook_login", sa.String(), nullable=True),
        sa.Column("webhook_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("TRUE"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account_id"),
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_accounts_account_id"),
        "accounts",
        ["account_id"],
        unique=False,
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_accounts_customer_id"),
        "accounts",
        ["customer_id"],
        unique=False,
        schema="hostaway",
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["hostaway.accounts.account_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_listings_account_id"),
        "listings",
        ["account_id"],
        unique=False,
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_listings_customer_id"),
        "listings",
        ["customer_id"],
        unique=False,
        schema="hostaway",
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["hostaway.accounts.account_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["listing_id"], ["hostaway.listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_reservations_account_id"),
        "reservations",
        ["account_id"],
        unique=False,
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_reservations_customer_id"),
        "reservations",
        ["customer_id"],
        unique=False,
        schema="hostaway",
    )
    op.create_table(
        "messages",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("raw_messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"], ["hostaway.accounts.account_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"], ["hostaway.reservations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("reservation_id"),
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_messages_account_id"),
        "messages",
        ["account_id"],
        unique=False,
        schema="hostaway",
    )
    op.create_index(
        op.f("ix_hostaway_messages_customer_id"),
        "messages",
        ["customer_id"],
        unique=False,
        schema="hostaway",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_hostaway_messages_customer_id"), table_name="messages", schema="hostaway"
    )
    op.drop_index(op.f("ix_hostaway_messages_account_id"), table_name="messages", schema="hostaway")
    op.drop_table("messages", schema="hostaway")
    op.drop_index(
        op.f("ix_hostaway_reservations_customer_id"), table_name="reservations", schema="hostaway"
    )
    op.drop_index(
        op.f("ix_hostaway_reservations_account_id"), table_name="reservations", schema="hostaway"
    )
    op.drop_table("reservations", schema="hostaway")
    op.drop_index(
        op.f("ix_hostaway_listings_customer_id"), table_name="listings", schema="hostaway"
    )
    op.drop_index(op.f("ix_hostaway_listings_account_id"), table_name="listings", schema="hostaway")
    op.drop_table("listings", schema="hostaway")
    op.drop_index(
        op.f("ix_hostaway_accounts_customer_id"), table_name="accounts", schema="hostaway"
    )
    op.drop_index(op.f("ix_hostaway_accounts_account_id"), table_name="accounts", schema="hostaway")
    op.drop_table("accounts", schema="hostaway")
    # ### end Alembic commands ###
