"""remove_webhook_auth_add_webhook_id

Revision ID: 3b359c691e02
Revises: eddb60bd5ad5
Create Date: 2025-10-22 15:27:05.107499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b359c691e02"
down_revision: Union[str, Sequence[str], None] = "eddb60bd5ad5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("webhook_id", sa.Integer(), nullable=True), schema="hostaway"
    )
    op.drop_column("accounts", "webhook_login", schema="hostaway")
    op.drop_column("accounts", "webhook_password", schema="hostaway")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("webhook_password", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="hostaway",
    )
    op.add_column(
        "accounts",
        sa.Column("webhook_login", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="hostaway",
    )
    op.drop_column("accounts", "webhook_id", schema="hostaway")
    # ### end Alembic commands ###
