"""add reservation_id unique constraint

Revision ID: 9fc7f1761139
Revises: 0bb7b9b7ad01
Create Date: 2025-07-16 16:01:36.968524

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "9fc7f1761139"
down_revision: Union[str, Sequence[str], None] = "0bb7b9b7ad01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_message_threads_reservation_id", "messages", ["reservation_id"], schema="hostaway"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_message_threads_reservation_id", "messages", schema="hostaway", type_="unique"
    )
    # ### end Alembic commands ###
