"""add_last_sync_at_to_accounts

Revision ID: eddb60bd5ad5
Revises: 2e07f6b55afd
Create Date: 2025-09-25 17:37:40.127098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eddb60bd5ad5"
down_revision: Union[str, Sequence[str], None] = "2e07f6b55afd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("last_sync_at", sa.TIMESTAMP(timezone=True), nullable=True),
        schema="hostaway",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "last_sync_at", schema="hostaway")
    # ### end Alembic commands ###
